(split)bug:100851 - Fixed java.lang.NoClassDefFoundError: org/json/JSONException caused by missing json.jar from common.java - Added jar build target and in manifest
https://bugzilla.zimbra.com/show_bug.cgi?id=100851

Copied from Perforce
 Change: 555461